# Generated by Django 5.1.5 on 2025-02-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
