# Generated by Django 5.1.5 on 2025-02-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_alter_review_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_user',
            new_name='review_user_id',
        ),
    ]
