# Generated by Django 5.1.5 on 2025-02-04 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0008_rename_review_user_review_review_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_user_id',
            new_name='review_user',
        ),
    ]
